---
version: "3"
services:
  postgres:
    container_name : postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/db:/var/lib/postgresql
  mongo:
    container_name : mongo_container
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo/db:/data/db
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:0.1.2
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
      EXTRA_ARGS: "--http-host 0.0.0.0 --relax-jolokia"
    volumes:
      - ./volumes/artemis/data:/artemis