---
version: "3"
services:
  postgres:
    container_name : postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/db:/var/lib/postgresql
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:0.1.2
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
      - "1883:1883"
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
      EXTRA_ARGS: "--http-host 0.0.0.0 --relax-jolokia"
    volumes:
      - ./volumes/artemis/data:/artemis
    networks:
      customnetwork:
        ipv4_address: 172.20.0.10
  web:
    image: nginx
    volumes:
      - ./volumes/nginx/templates:/etc/nginx/templates
    ports:
      - "8081:80"
    environment:
      - NGINX_SERVERNAME=locahost
      - NGINX_PORT=80
      - IP_ARTEMIS=172.20.0.10
      - PORT_ARTEMIS=8161
    networks:
      - customnetwork
networks:
  customnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1