---
version: "3"
services:
  postgres-command:
    container_name : postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/db:/var/lib/postgresql
  postgres-referenciel:
    container_name: postgres_container_query
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5UP3r53Cr37
      PGDATA: /data/postgres
    ports:
      - 5433:5432
    volumes:
      - ./volumes/postgres/dbQuery:/var/lib/postgresql
  mongo:
    container_name: mongo_container
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - 9200:9200
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
  artemis:
    container_name: artemis
    image: quay.io/artemiscloud/activemq-artemis-broker:0.1.2
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
      - "1883:1883"
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
      EXTRA_ARGS: "--http-host 0.0.0.0 --relax-jolokia"
    volumes:
      - ./volumes/artemis/data:/artemis
    networks:
      customnetwork:
        ipv4_address: 172.20.0.10
  web:
    image: nginx
    volumes:
      - ./volumes/nginx/templates:/etc/nginx/templates
    ports:
      - "8090:80"
    environment:
      - NGINX_SERVERNAME=locahost
      - NGINX_PORT=80
      - IP_ARTEMIS=172.20.0.10
      - PORT_ARTEMIS=8161
    networks:
      - customnetwork
networks:
  customnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1