package models.in;

public enum EventType {
    UNKNOWN,
    EVENT_CREATION,
    EVENT_DELETION,
    EVENT_UPDATE,
    RESOURCE_RESERVATION,
    RESOURCE_RELEASE,
    CUSTOMER_ENROLMENT,
    CUSTOMER_ENROLMENT_CANCELLATION,
    CUSTOMER_CREATION,
    CUSTOMER_UPDATE,
    TEACHER_ASSIGNATION,
    TEACHER_CREATION,
    RESOURCE_CREATION,
    TEACHER_DELETION,
    RESOURCE_DELETION
}
